<a href="https://colab.research.google.com/github/hyunkyu-Park/Deep-Learning-For-All/blob/main/Multi_variable_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 모두를 위한 딥러닝 시즌 1 Version



In [ ]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

tf.model = tf.keras.Sequential()

tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3))  # input_dim=3 gives multi-variable regression
tf.model.add(tf.keras.layers.Activation('linear'))  # this line can be omitted, as linear activation is default
# advanced reading https://towardsdatascience.com/activation-functions-neural-networks-1cbd9f8d91d6

In [ ]:
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 4         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [ ]:
history = tf.model.fit(x_data, y_data, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 234ms/step - loss: 9.7831
Epoch 2/100
1/1 [==============================] - 0s 10ms/step - loss: 9.7780
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 9.7728
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 9.7676
Epoch 5/100
1/1 [==============================] - 0s 6ms/step - loss: 9.7624
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 9.7572
Epoch 7/100
1/1 [==============================] - 0s 6ms/step - loss: 9.7520
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 9.7468
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 9.7417
Epoch 10/100
1/1 [==============================] - 0s 11ms/step - loss: 9.7365
Epoch 11/100
1/1 [==============================] - 0s 5ms/step - loss: 9.7313
Epoch 12/100
1/1 [==============================] - 0s 6ms/step - loss: 9.7261
Epoch 13/100
1/1 [==============================] - 0s 6

In [ ]:
y_predict = tf.model.predict(np.array([[72., 93., 90.]]))
print(y_predict)

[[176.19037]]


In [ ]:
y_predict = tf.model.predict(np.array([[73., 80., 75.]]))
print(y_predict)

[[155.70543]]


# 모두를 위한 딥러닝 시즌 2 Version

##03 - Multi-variable Linear Regression

In [1]:
import tensorflow as tf
import numpy as np

###Simple Example(2 variabels)

In [2]:
x1_data = [1, 0, 3, 0, 5]
x2_data = [0, 2, 0, 4, 0]
y_data  = [1, 2, 3, 4, 5]

W1 = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))
W2 = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))
b  = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))

learning_rate = tf.Variable(0.001)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = W1 * x1_data + W2 * x2_data + b
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))
    W1_grad, W2_grad, b_grad = tape.gradient(cost, [W1, W2, b])
    W1.assign_sub(learning_rate * W1_grad)
    W2.assign_sub(learning_rate * W2_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
          i, cost.numpy(), W1.numpy()[0], W2.numpy()[0], b.numpy()[0]))

    0 | 421.747559 |     1.0859 |    -9.2478 |   0.235725
   50 | 176.917908 |     0.9395 |    -5.9345 |   1.179017
  100 |  74.890381 |     0.7727 |    -3.7900 |   1.753182
  150 |  32.193108 |     0.6330 |    -2.3991 |   2.100188
  200 |  14.274767 |     0.5296 |    -1.4948 |   2.305742
  250 |   6.734056 |     0.4586 |    -0.9051 |   2.422436
  300 |   3.546256 |     0.4126 |    -0.5188 |   2.482974
  350 |   2.186060 |     0.3847 |    -0.2644 |   2.507898
  400 |   1.593866 |     0.3694 |    -0.0953 |   2.510215
  450 |   1.324829 |     0.3626 |     0.0184 |   2.498211
  500 |   1.192129 |     0.3615 |     0.0962 |   2.477190
  550 |   1.117285 |     0.3641 |     0.1507 |   2.450548
  600 |   1.067317 |     0.3691 |     0.1900 |   2.420474
  650 |   1.028355 |     0.3757 |     0.2194 |   2.388376
  700 |   0.994557 |     0.3832 |     0.2423 |   2.355160
  750 |   0.963451 |     0.3913 |     0.2610 |   2.321408
  800 |   0.933984 |     0.3996 |     0.2768 |   2.287493
  850 |   0.90

###Simple Example(2 variables with Matrix)

In [3]:
x_data = [
    [1., 0., 3., 0., 5.],
    [0., 2., 0., 4., 0.]
]
y_data  = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random.uniform((1, 2), -1.0, 1.0))
b = tf.Variable(tf.random.uniform((1,), -1.0, 1.0))

learning_rate = tf.Variable(0.001)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(W, x_data) + b # (1, 2) * (2, 5) = (1, 5)
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))

        W_grad, b_grad = tape.gradient(cost, [W, b])
        W.assign_sub(learning_rate * W_grad)
        b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
            i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], b.numpy()[0]))

    0 |  15.025357 |    -0.2622 |     0.2716 |  -0.202924
   50 |   3.556374 |     0.3836 |     0.5187 |   0.038538
  100 |   0.896526 |     0.6810 |     0.6672 |   0.157715
  150 |   0.252234 |     0.8172 |     0.7582 |   0.216674
  200 |   0.085124 |     0.8792 |     0.8150 |   0.245534
  250 |   0.037438 |     0.9073 |     0.8511 |   0.259079
  300 |   0.022157 |     0.9200 |     0.8743 |   0.264674
  350 |   0.016597 |     0.9259 |     0.8895 |   0.266052
  400 |   0.014273 |     0.9288 |     0.8997 |   0.265147
  450 |   0.013128 |     0.9305 |     0.9067 |   0.262986
  500 |   0.012444 |     0.9316 |     0.9116 |   0.260124
  550 |   0.011951 |     0.9326 |     0.9152 |   0.256874
  600 |   0.011542 |     0.9335 |     0.9179 |   0.253413
  650 |   0.011174 |     0.9344 |     0.9201 |   0.249846
  700 |   0.010830 |     0.9354 |     0.9219 |   0.246234
  750 |   0.010501 |     0.9363 |     0.9235 |   0.242614
  800 |   0.010184 |     0.9372 |     0.9249 |   0.239010
  850 |   0.00

###Hypothesis without b

In [4]:
import tensorflow as tf

# 앞의 코드에서 bias(b)를 행렬에 추가
x_data = [
    [1., 1., 1., 1., 1.], # bias(b)
    [1., 0., 3., 0., 5.], 
    [0., 2., 0., 4., 0.]
]
y_data  = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random.uniform((1, 3), -1.0, 1.0)) # [1, 3]으로 변경하고, b 삭제

learning_rate = 0.001
optimizer = tf.keras.optimizers.SGD(learning_rate)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(W, x_data) # b가 없다
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))

    grads = tape.gradient(cost, [W])
    optimizer.apply_gradients(grads_and_vars=zip(grads,[W]))
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.4f}".format(
            i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], W.numpy()[0][2]))

    0 |  17.293497 |    -0.3668 |    -0.2739 |     0.1515
   50 |   4.211652 |    -0.0998 |     0.3972 |     0.4532
  100 |   1.102621 |     0.0346 |     0.7046 |     0.6362
  150 |   0.319834 |     0.1031 |     0.8441 |     0.7492
  200 |   0.105668 |     0.1383 |     0.9068 |     0.8199
  250 |   0.040766 |     0.1562 |     0.9346 |     0.8647
  300 |   0.018919 |     0.1651 |     0.9466 |     0.8934
  350 |   0.010852 |     0.1691 |     0.9518 |     0.9121
  400 |   0.007632 |     0.1703 |     0.9541 |     0.9243
  450 |   0.006242 |     0.1700 |     0.9552 |     0.9324
  500 |   0.005580 |     0.1688 |     0.9558 |     0.9380
  550 |   0.005215 |     0.1671 |     0.9563 |     0.9418
  600 |   0.004977 |     0.1651 |     0.9568 |     0.9446
  650 |   0.004793 |     0.1630 |     0.9573 |     0.9466
  700 |   0.004634 |     0.1607 |     0.9579 |     0.9482
  750 |   0.004489 |     0.1584 |     0.9584 |     0.9495
  800 |   0.004351 |     0.1561 |     0.9590 |     0.9506
  850 |   0.00

###Custom Gradient
ㆍ tf.train.GradientDescentOptimizer(): optimizer  
ㆍ optimizer.apply_gradients(): update

In [5]:
# Multi-variable linear regression (1)

X = tf.constant([[1., 2.], 
                 [3., 4.]])
y = tf.constant([[1.5], [3.5]])

W = tf.Variable(tf.random.normal((2, 1)))
b = tf.Variable(tf.random.normal((1,)))

# Create an optimizer
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

n_epoch = 1000+1
print("epoch | cost")
for i in range(n_epoch):
    # Use tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        y_pred = tf.matmul(X, W) + b
        cost = tf.reduce_mean(tf.square(y_pred - y))

    # calculates the gradients of the loss
    grads = tape.gradient(cost, [W, b])
    
    # updates parameters (W and b)
    optimizer.apply_gradients(grads_and_vars=zip(grads, [W, b]))
    if i % 50 == 0:
        print("{:5} | {:10.6f}".format(i, cost.numpy()))

epoch | cost
    0 |   2.915952
   50 |   0.020451
  100 |   0.013983
  150 |   0.009560
  200 |   0.006536
  250 |   0.004469
  300 |   0.003055
  350 |   0.002089
  400 |   0.001428
  450 |   0.000977
  500 |   0.000668
  550 |   0.000456
  600 |   0.000312
  650 |   0.000213
  700 |   0.000146
  750 |   0.000100
  800 |   0.000068
  850 |   0.000047
  900 |   0.000032
  950 |   0.000022
 1000 |   0.000015


###Predicting exam score

In [6]:

# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# weights
w1 = tf.Variable(10.)
w2 = tf.Variable(10.)
w3 = tf.Variable(10.)
b  = tf.Variable(10.)

learning_rate = 0.000001

for i in range(1000+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
    
    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
      print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 | 5793889.5000
   50 |   64291.1562
  100 |     715.2903
  150 |       9.8461
  200 |       2.0152
  250 |       1.9252
  300 |       1.9210
  350 |       1.9177
  400 |       1.9145
  450 |       1.9114
  500 |       1.9081
  550 |       1.9050
  600 |       1.9018
  650 |       1.8986
  700 |       1.8955
  750 |       1.8923
  800 |       1.8892
  850 |       1.8861
  900 |       1.8829
  950 |       1.8798
 1000 |       1.8767


###Multi-variable Linear Regression(1)

In [7]:
# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# random weights
w1 = tf.Variable(tf.random.normal((1,)))
w2 = tf.Variable(tf.random.normal((1,)))
w3 = tf.Variable(tf.random.normal((1,)))
b  = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

for i in range(1000+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
    
    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
      print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 |   65949.9219
   50 |     739.8290
  100 |      16.2391
  150 |       8.1952
  200 |       8.0912
  250 |       8.0753
  300 |       8.0604
  350 |       8.0456
  400 |       8.0308
  450 |       8.0160
  500 |       8.0013
  550 |       7.9866
  600 |       7.9719
  650 |       7.9573
  700 |       7.9427
  750 |       7.9282
  800 |       7.9137
  850 |       7.8993
  900 |       7.8848
  950 |       7.8704
 1000 |       7.8561


###Multi-variable Linear Regression(2) - with Matrix

In [8]:
data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

# slice data
X = data[:, :-1]
y = data[:, [-1]]

W = tf.Variable(tf.random.normal((3, 1)))
b = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

# hypothesis, prediction function
def predict(X):
    return tf.matmul(X, W) + b

print("epoch | cost")

n_epochs = 2000
for i in range(n_epochs+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean((tf.square(predict(X) - y)))

    # calculates the gradients of the loss
    W_grad, b_grad = tape.gradient(cost, [W, b])

    # updates parameters (W and b)
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 100 == 0:
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

epoch | cost
    0 |  7841.2275
  100 |     6.0632
  200 |     5.0808
  300 |     5.0631
  400 |     5.0455
  500 |     5.0281
  600 |     5.0107
  700 |     4.9934
  800 |     4.9763
  900 |     4.9592
 1000 |     4.9422
 1100 |     4.9252
 1200 |     4.9084
 1300 |     4.8916
 1400 |     4.8750
 1500 |     4.8584
 1600 |     4.8419
 1700 |     4.8255
 1800 |     4.8092
 1900 |     4.7930
 2000 |     4.7768


In [9]:
W.numpy()

array([[0.02344068],
       [0.50658476],
       [1.4545549 ]], dtype=float32)

In [10]:
b.numpy()

array([1.4628913], dtype=float32)

In [11]:
tf.matmul(X, W) + b

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[152.79247],
       [183.49594],
       [180.55826],
       [198.814  ],
       [138.4275 ]], dtype=float32)>

###Predict

In [15]:
Y # labels, 실제값

[152.0, 185.0, 180.0, 196.0, 142.0]

In [16]:
predict(X).numpy() # prediction, 예측값

array([[152.79247],
       [183.49594],
       [180.55826],
       [198.814  ],
       [138.4275 ]], dtype=float32)

In [18]:
# 새로운 데이터에 대한 예측

predict([[ 89.,  95.,  92.],[ 84.,  92.,  85.]]).numpy()  

array([[185.49371],
       [173.67487]], dtype=float32)