<a href="https://colab.research.google.com/github/hyunkyu-Park/Deep-Learning-For-All/blob/main/Softmax_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Lab 6 Softmax Classifier
import tensorflow as tf
import numpy as np

x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)

nb_classes = 3

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim=4, units=nb_classes, use_bias=True))  # use_bias is True, by default

# use softmax activations: softmax = exp(logits) / reduce_sum(exp(logits), dim)
tf.model.add(tf.keras.layers.Activation('softmax'))

# use loss == categorical_crossentropy
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
_________________________________________________________________
activation (Activation)      (None, 3)                 0         
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [2]:
history = tf.model.fit(x_data, y_data, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 423ms/step - loss: 1.5858 - accuracy: 0.5000
Epoch 2/2000
1/1 [==============================] - 0s 10ms/step - loss: 1.2235 - accuracy: 0.5000
Epoch 3/2000
1/1 [==============================] - 0s 4ms/step - loss: 1.0254 - accuracy: 0.5000
Epoch 4/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.9781 - accuracy: 0.5000
Epoch 5/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.9571 - accuracy: 0.5000
Epoch 6/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.9391 - accuracy: 0.5000
Epoch 7/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.9238 - accuracy: 0.5000
Epoch 8/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.9101 - accuracy: 0.5000
Epoch 9/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.8987 - accuracy: 0.6250
Epoch 10/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.8885 - accuracy: 0.3750
Epoch 11/2000
1/

In [3]:
print('--------------')
# Testing & One-hot encoding
a = tf.model.predict(np.array([[1, 11, 7, 9]]))
print(a, tf.keras.backend.eval(tf.argmax(a, axis=1)))

print('--------------')
b = tf.model.predict(np.array([[1, 3, 4, 3]]))
print(b, tf.keras.backend.eval(tf.argmax(b, axis=1)))

print('--------------')
# or use argmax embedded method, predict_classes
c = tf.model.predict(np.array([[1, 1, 0, 1]]))
c_onehot = tf.model.predict_classes(np.array([[1, 1, 0, 1]]))
print(c, c_onehot)

print('--------------')
all = tf.model.predict(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))
all_onehot = tf.model.predict_classes(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))
print(all, all_onehot)

--------------
[[2.3188071e-02 9.7680140e-01 1.0546094e-05]] [1]
--------------
[[0.7216747  0.25066018 0.02766512]] [0]
--------------
[[2.1780918e-08 4.1248772e-04 9.9958748e-01]] [2]
--------------
[[2.3188071e-02 9.7680140e-01 1.0546104e-05]
 [7.2167486e-01 2.5066000e-01 2.7665118e-02]
 [2.1780918e-08 4.1248775e-04 9.9958748e-01]] [1 0 2]


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '
